### ISSUE TITLE
Can't do manual initialization

### ISSUE THREAD

**Issue by Maksi1994** [nolimits4web/swiper#2462]
I use ngx-swiper-wrapper of last version. I have some problem when I'm using him in my page. I think, that i can run manualy intialize in during use. For that i set init: false property in config and i wanted use swiperInstant.init() in my angular component, this solution helped, but when I was reload my component witch have swiper - i view this Error and my application can't work normaly.

> ERROR DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.
    at Dom7.removeClass (webpack-internal:///../../../../swiper/dist/js/swiper.js:126:77)
    at Swiper.removeClasses (webpack-internal:///../../../../swiper/dist/js/swiper.js:3118:7)
    at Swiper.destroy (webpack-internal:///../../../../swiper/dist/js/swiper.js:3685:14)
    at eval (webpack-internal:///../../../../ngx-swiper-wrapper/dist/ngx-swiper-wrapper.es5.js:331:32)
    at ZoneDelegate.invoke (webpack-internal:///../../../../zone.js/dist/zone.js:388:26)
    at Zone.run (webpack-internal:///../../../../zone.js/dist/zone.js:138:43)
    at NgZone.runOutsideAngular (webpack-internal:///../../../core/esm5/core.js:4896:69)
    at SwiperDirective.ngOnDestroy (webpack-internal:///../../../../ngx-swiper-wrapper/dist/ngx-swiper-wrapper.es5.js:330:23)
    at callProviderLifecycles (webpack-internal:///../../../core/esm5/core.js:12910:18)
    at callElementProvidersLifecycles (webpack-internal:///../../../core/esm5/core.js:12871:13)

**Comment by nolimits4web** [comment]
Sorry, how is it related to Swiper? You should probably raise an issue on `ngx-swiper-wrapper` or what you use
