### ISSUE TITLE
AddSlide function failed while there is no slide in wrapper

### ISSUE THREAD

**Issue by LockonS** [nolimits4web/swiper#2674]
While trying out the addSlide(index, slide) function, it appears that addSlide function will fail if there is no slide in slide wrapper.
And this is the output error of chrome.
```
TypeError: Cannot read property 'classList' of undefined
    at i.addClass (http://aishiguang.oss-cn-beijing.aliyuncs.com/cdn/static/swiper-4.3.3/js/swiper.min.js:12:2140)
    at t.updateSlidesClasses (http://aishiguang.oss-cn-beijing.aliyuncs.com/cdn/static/swiper-4.3.3/js/swiper.min.js:12:22813)
    at t.slideTo (http://aishiguang.oss-cn-beijing.aliyuncs.com/cdn/static/swiper-4.3.3/js/swiper.min.js:12:29017)
    at t.init (http://aishiguang.oss-cn-beijing.aliyuncs.com/cdn/static/swiper-4.3.3/js/swiper.min.js:12:57758)
    at new t (http://aishiguang.oss-cn-beijing.aliyuncs.com/cdn/static/swiper-4.3.3/js/swiper.min.js:12:56080)
```

**Comment by nolimits4web** [comment]
Can't replicate the issue, would be good to see live example with the issue
