### ISSUE TITLE
purifycss-webpack not working with swiper >=4.0.0

### ISSUE THREAD

**Issue by manuelbachl** [nolimits4web/swiper#2753]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: every single Version >=4.0.0 (3.4.2 works fine)
* Node Versions: 8.10.0 and 8.11.3
* npm Versions: 6.1.0 and 6.2.0
* webpack Version 4.12.0
* Platform/Target and Browser Versions: macOS

#### Apporach 1
I'm just importing the `swiper/dist/css/swiper.css` in my main.scss -> Build fails with this message:
```
(node:33449) UnhandledPromiseRejectionWarning: Error: undefined:10:17552: property missing ':'
at error (xxx/xxx/node_modules/css/lib/parse/index.js:62:15)
at declaration (xxx/xxx/node_modules/css/lib/parse/index.js:224:33)
at declarations (xxx/xxx/node_modules/css/lib/parse/index.js:253:19)
at rule (xxx/xxx/node_modules/css/lib/parse/index.js:561:21)
at rules (xxx/xxx/node_modules/css/lib/parse/index.js:118:70)
at stylesheet (xxx/xxx/node_modules/css/lib/parse/index.js:81:21)
at module.exports (xxx/xxx/node_modules/css/lib/parse/index.js:565:20)
at rework (xxx/xxx/node_modules/rework/index.js:27:21)
at CssTreeWalker.beginReading (xxx/xxx/node_modules/purify-css/lib/purifycss.js:568:24)
at purify (xxx/xxx/node_modules/purify-css/lib/purifycss.js:1009:10)
at xxx/xxx/server-build.js:119:21
at CSSPurgeEmitter.continueCSSProcess (xxx/xxx/node_modules/css-purge/lib/css-purge.js:6457:5)
at emitOne (events.js:116:13)
at CSSPurgeEmitter.emit (events.js:211:7)
at readReduceDeclarations (xxx/xxx/node_modules/css-purge/lib/css-purge.js:1594:13)
at processCSS (xxx/xxx/node_modules/css-purge/lib/css-purge.js:6507:5)
(node:33449) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:33449) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### Approach 2
Tried both custom build variants (http://idangero.us/swiper/api/#custom-build), both failing because of not finding airbnb linting settings which ARE installed in node modules

Currently it seems impossible to use swiper above Version 4.0.0 with purifycss-webpack (which is absolutely necessary in our VueJS-project)

### Expected Behavior
My build shouldn't fail
### Actual Behavior
see above

**Comment by nolimits4web** [comment]
Seems like not related to Swiper.

> both failing because of not finding airbnb linting settings which ARE installed in node modules

airbnb linting settings are not related to build process too

**Comment by manuelbachl** [comment]
Hmm myself I'm not using airbnb linting - this package is wanted by swipers package.json

But this issue only happens when using the custom build. I'd prefer to get the first option to work - I just want to import the swiper.css and still be able to build my project. Currently it's not possible as mentioned above because purifycss-webpack complains about the missing stuff (see error message in first post). Here I Can't do anything because it IS swiper related ;-)

My build succeeds when not importing swiper.css ;-)
