### ISSUE TITLE
swiper 6.x production build

### ISSUE THREAD

**Issue by 0101adm** [nolimits4web/swiper#3678]
* [x] bug

6.0.2
macOS

### What you did

SCRIPTS/BUILD-CONFIG.JS
```javascript
module.exports = {
	components : [
		'navigation',
		'pagination',
		'lazy',
		'controller',
		'effect-fade',
		'thumbs'
	],
	themeColor : '#007aff',
	colors     : {
		white : '#ffffff',
		black : '#000000'
	}
};
```
RUNNING
npm run build:prod

CONSOLE LOG
```javascript
fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir './package/components/navigation'
    at Object.fs.mkdirSync (fs.js:885:18)
    at components.forEach (/Users/aaronmiller/Documents/GitHub/swiper/swiper-6.0.1/scripts/build-js-core.js:115:8)
    at Array.forEach (<anonymous>)
    at build (/Users/aaronmiller/Documents/GitHub/swiper/swiper-6.0.1/scripts/build-js-core.js:114:14)
    at build (/Users/aaronmiller/Documents/GitHub/swiper/swiper-6.0.1/scripts/build.js:9:3)
    at Object.<anonymous> (/Users/aaronmiller/Documents/GitHub/swiper/swiper-6.0.1/scripts/build.js:15:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
```

### Expected Behavior
expected build files.

### Actual Behavior
build-time error.

**Comment by nolimits4web** [comment]
You need to update Node to ` > 10.12.0` which supports recursive directories creation
