### ISSUE TITLE
'MODULES' command not found at version 6.2.0

### ISSUE THREAD

**Issue by hugh2113** [nolimits4web/swiper#3820]
I am following Dist / Build at 6.2.0 on window 10 npm version 6.14.6
I run build:dev at 4.5.3 and 5.4.5 success but at 6.2.0
bash say 
```
'MODULES' command not found
'MODULES' command not found
'MODULES' command not found
'MODULES' command not found
(node:22084) UnhandledPromiseRejectionWarning: Error: Shell command exit with non zero code: 1
    at ChildProcess.<anonymous> (D:\#hugh\Desktop\swiper\node_modules\exec-sh\lib\exec-sh.js:73:15)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:22084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22084) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22084) UnhandledPromiseRejectionWarning: Error: Shell command exit with non zero code: 1
    at ChildProcess.<anonymous> (D:\#hugh\Desktop\swiper\node_modules\exec-sh\lib\exec-sh.js:73:15)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:22084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:22084) UnhandledPromiseRejectionWarning: Error: Shell command exit with non zero code: 1
    at ChildProcess.<anonymous> (D:\#hugh\Desktop\swiper\node_modules\exec-sh\lib\exec-sh.js:73:15)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:22084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:22084) UnhandledPromiseRejectionWarning: Error: Shell command exit with non zero code: 1
    at ChildProcess.<anonymous> (D:\#hugh\Desktop\swiper\node_modules\exec-sh\lib\exec-sh.js:73:15)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:22084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
'MODULES' command not found
(node:22084) UnhandledPromiseRejectionWarning: Error: Shell command exit with non zero code: 1
    at ChildProcess.<anonymous> (D:\#hugh\Desktop\swiper\node_modules\exec-sh\lib\exec-sh.js:73:15)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:22084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
'MODULES' command not found
(node:22084) UnhandledPromiseRejectionWarning: Error: Shell command exit with non zero code: 1
    at ChildProcess.<anonymous> (D:\#hugh\Desktop\swiper\node_modules\exec-sh\lib\exec-sh.js:73:15)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:22084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
```

**Comment by Daijobou** [comment]
Here the same with npm@6.14.8
Source: https://swiperjs.com/api/#custom-build

But its created successfull the packages.
