### ISSUE TITLE
ci: npm run build:prod not throwing error in ci

### ISSUE THREAD

**Issue by vltansky** [nolimits4web/swiper#4037]
https://travis-ci.org/github/nolimits4web/swiper/builds/748628636
```

(node:5409) UnhandledPromiseRejectionWarning: Error: ENOTEMPTY: directory not empty, rmdir './package/esm/less'
    at Object.rmdirSync (fs.js:684:3)
    at dirsToRemove.forEach (/home/travis/build/nolimits4web/swiper/scripts/build-js-core.js:76:8)
    at Array.forEach (<anonymous>)
    at buildCore (/home/travis/build/nolimits4web/swiper/scripts/build-js-core.js:75:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5409) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5409) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5409) UnhandledPromiseRejectionWarning: Error: ENOTEMPTY: directory not empty, rmdir './package/cjs/less'
    at Object.rmdirSync (fs.js:684:3)
    at dirsToRemove.forEach (/home/travis/build/nolimits4web/swiper/scripts/build-js-core.js:76:8)
    at Array.forEach (<anonymous>)
    at buildCore (/home/travis/build/nolimits4web/swiper/scripts/build-js-core.js:75:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5409) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

https://travis-ci.org/github/nolimits4web/swiper/builds/748844219
```
------------------------------------------------------------------------------
Building entry point 'swiper_angular'
------------------------------------------------------------------------------
- Compiling TypeScript sources through NGC
Successfully compiled 92 files with Babel (19350ms).
(node:5299) UnhandledPromiseRejectionWarning: Error: ENOTEMPTY: directory not empty, rmdir './package/esm/less'
    at Object.rmdirSync (fs.js:684:3)
    at dirsToRemove.forEach (/home/travis/build/nolimits4web/swiper/scripts/build-js-core.js:76:8)
    at Array.forEach (<anonymous>)
    at buildCore (/home/travis/build/nolimits4web/swiper/scripts/build-js-core.js:75:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5299) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5299) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✖ Compiling TypeScript sources through NGC
ERROR: src/angular/src/swiper.component.ts:29:32 - error TS2307: Cannot find module 'build/types' or its corresponding type declarations.
29 import { VirtualOptions } from 'build/types';
                                  ~~~~~~~~~~~~~
An unhandled exception occurred: src/angular/src/swiper.component.ts:29:32 - error TS2307: Cannot find module 'build/types' or its corresponding type declarations.
29 import { VirtualOptions } from 'build/types';
                                  ~~~~~~~~~~~~~
See "/tmp/ng-Awiuq9/angular-errors.log" for further details.
{ Error: Shell command exit with non zero code: 127
    at ChildProcess.<anonymous> (/home/travis/build/nolimits4web/swiper/node_modules/exec-sh/lib/exec-sh.js:73:15)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5) code: 127, stdout: '', stderr: '' }
Successfully compiled 92 files with Babel (22087ms).
(node:5299) UnhandledPromiseRejectionWarning: Error: ENOTEMPTY: directory not empty, rmdir './package/cjs/less'
    at Object.rmdirSync (fs.js:684:3)
    at dirsToRemove.forEach (/home/travis/build/nolimits4web/swiper/scripts/build-js-core.js:76:8)
    at Array.forEach (<anonymous>)
    at buildCore (/home/travis/build/nolimits4web/swiper/scripts/build-js-core.js:75:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5299) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

the same in GitHub Actions - https://github.com/nolimits4web/swiper/runs/1536120408?check_suite_focus=true.

**Comment by vltansky** [comment]
https://github.com/nolimits4web/swiper/pull/4031 PR include a fix for `import { VirtualOptions } from 'build/types';`
#4038 fixes CI error handler
