### ISSUE TITLE
Error in 6.4.9 with calling JQuery add class.

### ISSUE THREAD

**Issue by devwork-web** [nolimits4web/swiper#4155]
Swiper Version: 6.4.9
JQuery Version: 3.5.1

Not seeing the images; Swiper failed to start.

jquery.min.js:2 jQuery.Deferred exception: ** Cannot read property 'addClass' of undefined TypeError: Cannot read property 'addClass' of undefined**
    at t.addClasses (https://unpkg.com/swiper/swiper-bundle.min.js:13:61231)
    at t.r.init (https://unpkg.com/swiper/swiper-bundle.min.js:13:67366)
    at new t (https://unpkg.com/swiper/swiper-bundle.min.js:13:64477)
    at HTMLDocument.<anonymous> (https://peppol.network/wp-content/themes/onetf_wp_theme/assets/js/script.js:3:18)
    at e (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js:2:30005)
    at t (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js:2:30307) undefined
S.Deferred.exceptionHook @ jquery.min.js:2
t @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
B @ jquery.min.js:2
**jquery.min.js:2 Uncaught TypeError: Cannot read property 'addClass' of undefined**
    at t.addClasses (addClasses.js:42)
    at t.r.init (core-class.js:448)
    at new t (core-class.js:234)
    at HTMLDocument.<anonymous> (script.js:3)
    at e (jquery.min.js:2)
    at t (jquery.min.js:2)
addClasses @ addClasses.js:42
r.init @ core-class.js:448
t @ core-class.js:234
(anonymous) @ script.js:3
e @ jquery.min.js:2
t @ jquery.min.js:2
setTimeout (async)
S.readyException @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
e @ jquery.min.js:2
t @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
t @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
B @ jquery.min.js:2

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by allekss90** [comment]
the same issue in 6.4.9, on 6.4.8 - ok
