### ISSUE TITLE
Cannot read property 'split' of undefined when resizing

### ISSUE THREAD

**Issue by jhoy1020** [nolimits4web/swiper#4531]
- Swiper Version: 6.5.9
- Platform/Target and Browser Versions: Windows, Chrome

I resized the browser where swiper was on and got this error.

![image](https://user-images.githubusercontent.com/11131037/117450553-5e83d380-af0f-11eb-8c46-4a8d2fdfd0c7.png)

**Comment by nolimits4web** [comment]
Would be super helpful to see the fiddle/codesandbox with the issue

**Comment by nolimits4web** [comment]
Closing due to inactivity, missing demo and/or no responses from issue author

**Comment by Kenji94** [comment]
We have the same issue but it's not happening only when resizing.
The error is quite random and happens 1/20 times. I cannot reproduce it on fiddle/codesandbox.
After the error, the page becomes empty/white and it's a real issue.

`Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'split')
TypeError: Cannot read properties of undefined (reading 'split')
    at https://neovel.io/24-es2015.1e9406151554b28a2fbb.js:1:14911
    at Array.map (<anonymous>)...
  at ? (node_modules/dom7/dom7.esm.js:254:14)
  at Array.map(<anonymous>)
  at removeClass(node_modules/dom7/dom7.esm.js:253:38)
  at destroy(node_modules/swiper/esm/components/navigation/navigation.js:111:15)
  at apply(node_modules/swiper/esm/components/navigation/navigation.js:150:25)
  at ? (node_modules/swiper/esm/components/core/events-emitter.js:104:24)
  at Array.forEach(<anonymous>)
  at ? (node_modules/swiper/esm/components/core/events-emitter.js:103:37)
  at Array.forEach(<anonymous>)
  at emit(node_modules/swiper/esm/components/core/events-emitter.js:95:17)
  at destroy(node_modules/swiper/esm/components/core/core-class.js:587:12)
  at apply(node_modules/swiper/__ivy_ngcc__/angular/fesm2015/swiper_angular.js:930:75)
  at invoke(node_modules/zone.js/dist/zone-evergreen.js:364:30)
  at run(node_modules/zone.js/dist/zone-evergreen.js:123:47)
  at runOutsideAngular(webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:41542:91)
  at call(node_modules/swiper/__ivy_ngcc__/angular/fesm2015/swiper_angular.js:928:22)
  at ? (webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14459:28)
  at cleanUpView(webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14442:1)
  at ? (webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14122:47)
  at destroyLView(webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14096:1)
  at destroy(webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:15174:9)
  at destroy(webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:34245:55)
  at deactivate(webpack:/node_modules/@angular/router/__ivy_ngcc__/fesm2015/router.js:9122:28)
  at deactivateRouteAndOutlet(webpack:/node_modules/@angular/router/__ivy_ngcc__/fesm2015/router.js:4023:32)
  at deactivateRouteAndItsChildren(webpack:/node_modules/@angular/router/__ivy_ngcc__/fesm2015/router.js:3981:18)
  at callback(webpack:/node_modules/@angular/router/__ivy_ngcc__/fesm2015/router.js:4020:28)
  at forEach(webpack:/node_modules/@angular/router/__ivy_ngcc__/fesm2015/router.js:1455:13)
  at deactivateRouteAndOutlet(webpack:/node_modules/@angular/router/__ivy_ngcc__/fesm2015/router.js:4015:13)
  at deactivateRouteAndItsChildren(webpack:/node_modules/@angular/router/__ivy_ngcc__/fesm2015/router.js:3981:18)
  at deactivateRoutes(webpack:/node_modules/@angular/router/__ivy_ngcc__/fesm2015/router.js:3966:22)
  at ? (webpack:/node_modules/@angular/router/__ivy_ngcc__/fesm2015/router.js:3923:18)
  at Array.forEach(<anonymous>)
  at deactivateChildRoutes(webpack:/node_modules/@angular/router/__ivy_ngcc__/fesm2015/router.js:3916:29)
  at activate(webpack:/node_modules/@angular/router/__ivy_ngcc__/fesm2015/router.js:3900:14)
  at call(webpack:/node_modules/@angular/router/__ivy_ngcc__/fesm2015/router.js:3875:10)
  at _next(webpack:/node_modules/rxjs/_esm2015/internal/operators/map.js:29:35)
  at next(webpack:/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:18)
  at _next(webpack:/node_modules/rxjs/_esm2015/internal/operators/tap.js:46:26)
  at next(webpack:/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:18)
  at _next(webpack:/node_modules/rxjs/_esm2015/internal/operators/map.js:35:26)
  at next(webpack:/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:18)
  at notifyNext(webpack:/node_modules/rxjs/_esm2015/internal/operators/switchMap.js:66:26)
  at _next(webpack:/node_modules/rxjs/_esm2015/internal/innerSubscribe.js:10:21)
  at next(webpack:/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:18)
  at _next(webpack:/node_modules/rxjs/_esm2015/internal/operators/map.js:35:26)
  at next(webpack:/node_modules/rxjs/_esm2015/internal/Subscriber.js:49:18)
  at _subscribe(webpack:/node_modules/rxjs/_esm2015/internal/util/subscribeToArray.js:3:20)
  at _trySubscribe(webpack:/node_modules/rxjs/_esm2015/internal/Observable.js:42:25)
  at subscribe(webpack:/node_modules/rxjs/_esm2015/internal/Observable.js:28:22)
  at o.call(webpack:/node_modules/rxjs/_esm2015/internal/operators/map.js:16:23)`

**Comment by danielbigler** [comment]
@nolimits4web I created a Codesandbox that reproduces the issue: [Codesandbox](https://codesandbox.io/s/eager-meadow-jb96oy).
Just resize the window (desktop -> mobile) and scroll through the slides.
![image](https://user-images.githubusercontent.com/13196221/228508518-0b2544cc-3253-4577-befa-c9a917400edd.png)

Can we please reopen this issue? 🙂

**Comment by Kenji94** [comment]
+1
