### ISSUE TITLE
Swiper 7: Cannot find module 'swiper/svelte'

### ISSUE THREAD

**Issue by mweissen** [nolimits4web/swiper#4945]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/sveltekit-swiper-7-coq4t

### Bug description

The version in codesandbox works fine. But when I copy the source code into a new installation of Sveltekit to `/src/routes/s.svelte` I get 

```
SvelteKit v1.0.0-next.165

  network: not exposed
  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network


09:51:21 [vite] Error when evaluating SSR module /src/routes/s.svelte:
Error: Cannot find module 'swiper/svelte' from 'C:/Svelte/tw09swipe/src/routes'
    at Function.resolveSync [as sync] (C:\Svelte\tw09swipe\node_modules\resolve\lib\sync.js:102:15)
    at resolveFrom$3 (C:\Svelte\tw09swipe\node_modules\vite\dist\node\chunks\dep-9f74b403.js:4081:29)
    at resolve (C:\Svelte\tw09swipe\node_modules\vite\dist\node\chunks\dep-9f74b403.js:75136:22)
    at nodeRequire (C:\Svelte\tw09swipe\node_modules\vite\dist\node\chunks\dep-9f74b403.js:75115:25)
    at ssrImport (C:\Svelte\tw09swipe\node_modules\vite\dist\node\chunks\dep-9f74b403.js:75057:20)
    at eval (/src/routes/s.svelte:7:37)
    at async instantiateModule (C:\Svelte\tw09swipe\node_modules\vite\dist\node\chunks\dep-9f74b403.js:75100:9)

```	
Is this a mistake by Sveltekit, Vite or Swiper?

### Expected Behavior

Lioke the code in the codesandbox

### Actual Behavior

Error message: Cannot find module 'swiper/svelte'

### Swiper version

7.0.5

### Platform/Target and Browser Versions

Windows 10, Version 93.0.4577.63 (Offizieller Build) (64-Bit)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
#4871
