### ISSUE TITLE
Swiper build issue with SvelteKit

### ISSUE THREAD

**Issue by onderbakirtas** [nolimits4web/swiper#5299]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/onderbakirtas/swiper-svelte-issue

### Bug description

Swiper does not build on either local or any serverless platform (I use Vercel). Here is the Vercel build output.

```bash
Cloning github.com/onderbakirtas/swiper-svelte-issue (Branch: main, Commit: 9237298)
Cloning completed: 295.736ms
Analyzing source code...
Installing build runtime...
Build runtime installed: 3.012s
Looking up build cache...
Build Cache not found
Detected package.json
Installing dependencies...
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 3.38s.
Running "yarn run build"
yarn run v1.22.17
$ svelte-kit build
vite v2.7.3 building for production...
transforming...
✓ 127 modules transformed.
rendering chunks...
.svelte-kit/output/client/_app/manifest.json                            1.27 KiB
.svelte-kit/output/client/_app/start-1363be96.js                        18.40 KiB / gzip: 6.82 KiB
.svelte-kit/output/client/_app/layout.svelte-439b6fae.js                0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/error.svelte-03615a84.js                 1.56 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/pages/index.svelte-fc48853d.js           2.27 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/assets/start-61d1577b.css                0.16 KiB / gzip: 0.15 KiB
.svelte-kit/output/client/_app/assets/pages/index.svelte-b0a7d995.css   5.34 KiB / gzip: 2.53 KiB
.svelte-kit/output/client/_app/chunks/vendor-2ff27e93.js                82.17 KiB / gzip: 25.87 KiB
vite v2.7.3 building SSR bundle for production...
transforming...
✓ 12 modules transformed.
rendering chunks...
.svelte-kit/output/server/app.js                      0.09 KiB
.svelte-kit/output/server/chunks/app-45cfc0e3.js      7.81 KiB
.svelte-kit/output/server/chunks/layout-1dfdd97a.js   0.25 KiB
.svelte-kit/output/server/chunks/error-4381ba71.js    0.74 KiB
.svelte-kit/output/server/chunks/index-3a5285df.js    1.25 KiB
Run npm run preview to preview your production build locally.
> Using @sveltejs/adapter-auto
 > node_modules/swiper/svelte/swiper-svelte.js:14:24: error: No loader is configured for ".svelte" files: node_modules/swiper/svelte/swiper-slide.svelte
    14 │ import SwiperSlide from './swiper-slide.svelte';
       ╵                         ~~~~~~~~~~~~~~~~~~~~~~~
 > node_modules/swiper/svelte/swiper-svelte.js:13:19: error: No loader is configured for ".svelte" files: node_modules/swiper/svelte/swiper.svelte
    13 │ import Swiper from './swiper.svelte';
       ╵                    ~~~~~~~~~~~~~~~~~
> Build failed with 2 errors:
node_modules/swiper/svelte/swiper-svelte.js:13:19: error: No loader is configured for ".svelte" files: node_modules/swiper/svelte/swiper.svelte
node_modules/swiper/svelte/swiper-svelte.js:14:24: error: No loader is configured for ".svelte" files: node_modules/swiper/svelte/swiper-slide.svelte
Error: Build failed with 2 errors:
node_modules/swiper/svelte/swiper-svelte.js:13:19: error: No loader is configured for ".svelte" files: node_modules/swiper/svelte/swiper.svelte
node_modules/swiper/svelte/swiper-svelte.js:14:24: error: No loader is configured for ".svelte" files: node_modules/swiper/svelte/swiper-slide.svelte
    at failureErrorWithLog (/vercel/path0/node_modules/esbuild/lib/main.js:1493:15)
    at /vercel/path0/node_modules/esbuild/lib/main.js:1151:28
    at buildResponseToResult (/vercel/path0/node_modules/esbuild/lib/main.js:1149:7)
    at /vercel/path0/node_modules/esbuild/lib/main.js:1258:14
    at /vercel/path0/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/vercel/path0/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/vercel/path0/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1
```

### Expected Behavior

Work as expected like in dev mode.

### Actual Behavior

It doesn't build.

### Swiper version

7.3.3

### Platform/Target and Browser Versions

Windows 10, All Browswers

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by slackers123** [comment]
According to my research, the problem you are facing can be solved by adding `"svelte": "./swiper.esm.js"` to `"node_modules/swiper/package.json" `

**Comment by nolimits4web** [comment]
should be fixed by https://github.com/nolimits4web/swiper/pull/5301
