### ISSUE TITLE
Swiper breaks build on Nuxt 3

### ISSUE THREAD

**Issue by milos5593** [nolimits4web/swiper#5842]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/nuxt-starter-k7kdqv?file=components%2FSiteSlider.vue,pages%2Findex.vue

### Bug description

When running yarn generate option in Nuxt 3 application build breaks with the following error.

```shell
ERROR  [nuxt] [request error] Cannot find module '/home/projects/nuxt-starter-k7kdqv/.nuxt/prerender/chunks/app/modules/navigation/navigation.js' imported from /home/projects/nuxt-starter-k7kdqv/.nuxt/prerender/chunks/app/server.mjs
  at InternalError.get (https://nuxt-starter-k7kdqv.w.staticblitz.com/blitz.e40b17327b4f777f5dccacbb86b346b09cdd4176.js:6:292488)  
  at normalizeError (./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:278:24)  
  at Object.errorhandler [as onError] (./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:297:57)  
  at nodeHandler (./node_modules/h3/dist/index.mjs:431:23)  
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:28:17)  
  at async generateRoute (./node_modules/nitropack/dist/chunks/prerender.mjs:2507:17)  
  at async Module.prerender (./node_modules/nitropack/dist/chunks/prerender.mjs:2537:22)  
  at async eval (./node_modules/nuxt/dist/index.mjs:1227:7)  
  at async build (./node_modules/nuxt/dist/index.mjs:1672:5)  
  at async Object.invoke (./node_modules/nuxi/dist/chunks/build.mjs:56:5)  
  at async Object.invoke (./node_modules/nuxi/dist/chunks/generate.mjs:43:5)  
  at async _main (./node_modules/nuxi/dist/cli.mjs:61:20)
```

### Expected Behavior

Build passes without errors.

### Actual Behavior

Build breaks with the error message.

### Swiper version

8.2.6

### Platform/Target and Browser Versions

macOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Ismet1999** [comment]
I tried the following link. It helped https://github.com/nuxt/framework/issues/5348

**Comment by nolimits4web** [comment]
Closing as not related to Swiper
