### ISSUE TITLE
No swiping over nested shadow doms

### ISSUE THREAD

**Issue by stefanholzapfel** [nolimits4web/swiper#6063]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-default-forked-0viqjr?file=/index.html

### Bug description

Since upgrading to the latest version of swiper (8.4.0), swiping throws an error when started over an embedded shadow dom. 

I used a simple webcomponent from shoelace to showcase the issue in codesandbox. Just try to swipe when starting over the progress ring webcomponent. Please note that the error is not thrown to the embedded console but to the browsers console:

```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at V.L (onTouchStart.js:55:25)
```
This behavior is new, until recently I was working with embedded web components without any issues.

I guess it's a typo in https://github.com/nolimits4web/swiper/commit/8df7edffb8a30250298f5b5978f5b833f08ee4f4 line 55.
I added a comment there.

### Expected Behavior

Don't throw an error when start swiping over nested shadowDOM

### Swiper version

8.4.0

### Platform/Target and Browser Versions

Ubuntu / Chromium

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by realityfilter** [comment]
Same here. Thanks for reporting.

**Comment by Allan-Nava** [comment]
Same here:

```

TypeError: Cannot read properties of undefined (reading 'includes')
    at isChildSwiperSlide (file:///app/node_modules/swiper/react/get-children.js:4:47)
    at file:///app/node_modules/swiper/react/get-children.js:28:9
    at Array.forEach (<anonymous>)
    at getChildren (file:///app/node_modules/swiper/react/get-children.js:27:29)
    at file:///app/node_modules/swiper/react/swiper.js:47:7
    at Wc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
    at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:479)
    at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)

```

**Comment by johnark88** [comment]
![Screen Shot 2022-09-14 at 11 56 39 AM](https://user-images.githubusercontent.com/19443818/190258698-d7a2621b-75a9-4363-8ebf-8f71fbd3f405.png)

**Comment by jay-herrera** [comment]
Same error. Had to revert to 8.3.2

**Comment by Shane-Geary** [comment]
Same error here. Upgrading from a working version of 8.3.2 broke the library

**Comment by Allan-Nava** [comment]
So the solution is downgrade to 8.2.4? 

`
    "swiper": "8.2.4",`

**Comment by stefanholzapfel** [comment]
@johnark88 @Allan-Nava I'm not sure we are talking about the same error (even if they might be connected).

The reported error looks like it comes from introducing a new helper variable ([eventPath](https://github.com/nolimits4web/swiper/commit/8df7edffb8a30250298f5b5978f5b833f08ee4f4#diff-aa77f72552f65ca8bf3762d541b7dd5ba0eaba987c5d1e590b33c9d56beabef7R49)) but using it only in the [if condition](https://github.com/nolimits4web/swiper/commit/8df7edffb8a30250298f5b5978f5b833f08ee4f4#diff-aa77f72552f65ca8bf3762d541b7dd5ba0eaba987c5d1e590b33c9d56beabef7R54) and not in the [assignment](https://github.com/nolimits4web/swiper/commit/8df7edffb8a30250298f5b5978f5b833f08ee4f4#diff-aa77f72552f65ca8bf3762d541b7dd5ba0eaba987c5d1e590b33c9d56beabef7L49).

So before the change, the variable that get's assigned (event.path[0]) was part of the if condition and therefore not assigned if undefined. But now the helper variable is checked, which might have a value while event.path is nullish.
