### ISSUE TITLE
swiper v9 doesn't work with storyshots

### ISSUE THREAD

**Issue by king-of-emotion** [nolimits4web/swiper#6377]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/king-of-emotion/swiper-test-app

### Bug description

I use swiper with storybook and storyshots. swiper v9 does not work with storyshots, but v8 does work.
I prepare reproduction code in my swiper-test-app repository.

I tried to fix this bug, I found the following code can fix it.
```diff
  const swiper = this;
+ this.recalcSlides
  const { params, slidesEl } = swiper;
```
in [loopCreate](https://github.com/nolimits4web/swiper/blob/master/src/core/loop/loopCreate.js)
But, I don't know about swiper core code, so if you know of a better way, please let me know or fix this problem.
Sorry if I'm wrong with my code, please help.
### Expected Behavior

work with storyshots.

### Actual Behavior

if `yarn test` you get error message like bellow
```
TypeError: Cannot read properties of undefined (reading 'swiperSlideSize')

      at Swiper.swiperSlideSize [as slidesPerViewDynamic] (node_modules/swiper/core/core.js:264:43)
      at Swiper.slidesPerViewDynamic [as loopFix] (node_modules/swiper/core/loop/loopFix.js:38:66)
      at Swiper.loopFix [as loopCreate] (node_modules/swiper/core/loop/loopCreate.js:13:10)
      at Swiper.loopCreate [as init] (node_modules/swiper/core/core.js:474:14)
      at init (node_modules/swiper/components-shared/mount-swiper.js:24:10)
      at node_modules/swiper/react/swiper.js:118:16
      at commitHookEffectListMount (node_modules/react-dom/cjs/react-dom.development.js:23049:26)
      at commitLayoutEffectOnFiber (node_modules/react-dom/cjs/react-dom.development.js:23172:15)
      at commitLayoutMountEffects_complete (node_modules/react-dom/cjs/react-dom.development.js:24578:9)
      at commitLayoutEffects_begin (node_modules/react-dom/cjs/react-dom.development.js:24564:7)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:24502:3)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:26779:5)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:26638:5)
      at finishConcurrentRender (node_modules/react-dom/cjs/react-dom.development.js:25937:9)
      at performConcurrentWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:25765:7)
      at flushActQueue (node_modules/react/cjs/react.development.js:2665:24)
      at act (node_modules/react/cjs/react.development.js:2580:11)
      at node_modules/@testing-library/react/dist/act-compat.js:63:25
      at renderRoot (node_modules/@testing-library/react/dist/pure.js:159:26)
      at render (node_modules/@testing-library/react/dist/pure.js:246:10)
      at getRenderedTree (node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/react/renderTree.js:24:18)
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:9:24
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:29:24)
```

### Swiper version

v9.0.0 or later

### Platform/Target and Browser Versions

macOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by TomSmedley** [comment]
I'm also getting the error `Uncaught TypeError: Cannot read properties of undefined (reading 'swiperSlideSize')` since V9. basically from what I can tell, slidesPerView: auto doesn't work.

**Comment by king-of-emotion** [comment]
This error occurs when slidesPerView: auto, centeredSlides: true, loop: true.
Removing either of these will allow storyshots to generate snapshots.

**Comment by king-of-emotion** [comment]
Hi! This issue is likely to be resolved by https://github.com/nolimits4web/Swiper/commit/36ef2e608843b4c83a5dc7ecde30aa71794f639e . Thank you very much.
