### ISSUE TITLE
Breaks when slides per view is set to auto for virtual slides

### ISSUE THREAD

**Issue by yunchanpaik** [nolimits4web/swiper#6695]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-virtual-slides-forked-1ig9c5?file=%2Fsrc%2FApp.jsx%3A47%2C30

### Bug description

When `slidesPerView` is set to `auto` for virtual slides, I get the following error:

```
caught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Swiper.updateSlides (updateSlides.js:99:27)
    at Swiper.init (core.js:455:12)
    at mountSwiper (mount-swiper.js:24:10)
    at swiper.js:118:5
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at commitLayoutEffectOnFiber (react-dom.development.js:23268:17)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:9)
    at commitLayoutEffects_begin (react-dom.development.js:24674:7)
    at commitLayoutEffects (react-dom.development.js:24612:3)
    at commitRootImpl (react-dom.development.js:26823:5)
```

The reproduction link simply sets the `slidesPerView` from the Virtual slides demo page for React.

This issue has been asked twice in the discussion board, but no answer has been provided yet.

### Swiper version

9.3.2

### Platform/Target and Browser Versions

macOS Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by yunchanpaik** [comment]
My bad. duplicate of #2287
