### ISSUE TITLE
Swiper inside Angular CDK Drag&Drop

### ISSUE THREAD

**Issue by Marius-Romanus** [nolimits4web/swiper#7116]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/Marius-Romanus/bug-angular-swiper

### Bug description

Hello, I'm not really sure if this error belongs to swiper, or to the drag-drop of the angular cdk.

When you insert swiper into a draggable element of the Angular CDK and try to swipe, the following error appears in the console:

`zone.js:1681 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at DragRef._getPointerPositionInElement (drag-drop.mjs:1081:64)
    at DragRef._initializeDragSequence (drag-drop.mjs:864:24)
    at DragRef._pointerDown (drag-drop.mjs:394:22)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Zone.runTask (zone.js:173:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:483:34)
    at invokeTask (zone.js:1631:18)
    at globalCallback (zone.js:1662:29)
    at HTMLDivElement.globalZoneAwareCallback (zone.js:1695:16)
    at Swiper.onAny (swiper-element-bundle.mjs:173:15)`

<img width="369" alt="image" src="https://github.com/nolimits4web/swiper/assets/18282247/fb52dc39-b35d-4b5e-a9eb-8ad0910ac67f">

Thanks, greetings!

### Swiper version

10.3.1

### Platform/Target and Browser Versions

Windows 11, Node v18.17.1, Chrome v118.0.5993.70 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Sorry, if you are not sure if the error belongs to Swiper, we are not sure either
