### ISSUE TITLE
Swiper doesn't work with Svelte: Internal server error: Missing "./svelte" specifier in "swiper"

### ISSUE THREAD

**Issue by boxabirds** [nolimits4web/swiper#7374]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/boxabirds/brokenswiper-svelte

### Bug description

Hi I have created a basic demo for Swiper + SvelteKit and it's not working.  from that link you can see my `package.json` with all its dependencies. I don't see a Svelte category so I've put it here. Maybe you've dropped support for Svelte and that's the issue? 

**Internal server error: Missing "./svelte" specifier in "swiper"**

The error when going to the web page and doing `npm run dev` is this
```
1:25:06 PM [vite] page reload src/routes/+page.svelte
Internal server error: Missing "./svelte" specifier in "swiper" package
  Plugin: vite:import-analysis
  File: /../brokenswiper-svelte/swiperdemo/src/routes/+page.svelte
      at e (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:47465:25)
      at n (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:47465:627)
      at o (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:47465:1297)
      at resolveExportsOrImports (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:48144:20)
      at resolveDeepImport (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:48163:31)
      at tryNodeResolve (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:47888:20)
      at Context.resolveId (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:47649:28)
      at Object.resolveId (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:50880:64)
      at async TransformContext.resolve (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:50571:23)
      at async normalizeUrl (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:65697:34)
Error: Missing "./svelte" specifier in "swiper" package
    at e (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:47465:25)
    at n (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:47465:627)
    at o (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:47465:1297)
    at resolveExportsOrImports (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:48144:20)
    at resolveDeepImport (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:48163:31)
    at tryNodeResolve (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:47888:20)
    at Context.resolveId (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:47649:28)
    at Object.resolveId (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:50880:64)
    at async TransformContext.resolve (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:50571:23)
    at async normalizeUrl (file:///../brokenswiper-svelte/swiperdemo/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:65697:34) {
  plugin: 'vite:import-analysis',
  id: '/../brokenswiper-svelte/swiperdemo/src/routes/+page.svelte',
  pluginCode: '/* src/routes/+page.svelte generated by Svelte v4.2.12 */\n' +
    'import { create_ssr_component, validate_component } from "svelte/internal";\n' +
    '\n' +
    "import { onMount } from 'svelte';\n" +
    "import { Swiper, SwiperSlide } from 'swiper/svelte';\n" +
    "import 'swiper/css';\n" +
    '\n' +
    'const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {\n' +
    '\tlet swiperInstance;\n' +
    '\n' +
    '\tonMount(() => {\n' +
    '\t\tswiperInstance.slideNext();\n' +
    '\t});\n' +
    '\n' +
    '\tlet $$settled;\n' +
    '\tlet $$rendered;\n' +
    '\tlet previous_head = $$result.head;\n' +
    '\n' +
    '\tdo {\n' +
    '\t\t$$settled = true;\n' +
    '\n' +
    '\t\t// $$result.head is mutated by the literal expression\n' +
    "\t\t// need to reset it if we're looping back to prevent duplication\n" +
    '\t\t$$result.head = previous_head;\n' +
    '\n' +
    '\t\t$$rendered = `${validate_component(Swiper, "Swiper").$$render(\n' +
    '\t\t\t$$result,\n' +
    '\t\t\t{ swiper: swiperInstance },\n' +
    '\t\t\t{\n' +
    '\t\t\t\tswiper: $$value => {\n' +
    '\t\t\t\t\tswiperInstance = $$value;\n' +
    '\t\t\t\t\t$$settled = false;\n' +
    '\t\t\t\t}\n' +
    '\t\t\t},\n' +
    '\t\t\t{\n' +
    '\t\t\t\tdefault: () => {\n' +
    '\t\t\t\t\treturn `${validate_component(SwiperSlide, "SwiperSlide").$$render($$result, {}, {}, {\n' +
    '\t\t\t\t\t\tdefault: () => {\n' +
    '\t\t\t\t\t\t\treturn `Slide 1`;\n' +
    '\t\t\t\t\t\t}\n' +
    '\t\t\t\t\t})} ${validate_component(SwiperSlide, "SwiperSlide").$$render($$result, {}, {}, {\n' +
    '\t\t\t\t\t\tdefault: () => {\n' +
    '\t\t\t\t\t\t\treturn `Slide 2`;\n' +
    '\t\t\t\t\t\t}\n' +
    '\t\t\t\t\t})} ${validate_component(SwiperSlide, "SwiperSlide").$$render($$result, {}, {}, {\n' +
    '\t\t\t\t\t\tdefault: () => {\n' +
    '\t\t\t\t\t\t\treturn `Slide 3`;\n' +
    '\t\t\t\t\t\t}\n' +
    '\t\t\t\t\t})}`;\n' +
    '\t\t\t\t}\n' +
    '\t\t\t}\n' +
    '\t\t)}`;\n' +
    '\t} while (!$$settled);\n' +
    '\n' +
    '\treturn $$rendered;\n' +
    '});\n' +
    '\n' +
    'export default Page;'
}```

### Expected Behavior

It should work

### Actual Behavior

Internal server error

### Swiper version

"swiper": "^11.0.7"

### Platform/Target and Browser Versions

Any

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by boxabirds** [comment]
Ok I see I need to use Swiper Element instead
