### ISSUE TITLE
react__WEBPACK_IMPORTED_MODULE_0__.createContext is not a function in Next.js 14.2.3

### ISSUE THREAD

**Issue by ItsRemix** [nolimits4web/swiper#7568]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/nice-smoke-zs3cqt

### Bug description

⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at eval (./src/app/page.tsx:14:70)
    at (rsc)/./src/app/page.tsx (C:\GitHub\bnfc.cc\.next\server\app\page.js:234:1)
    at Function.__webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at async Promise.all (index 0)
digest: "235361954"
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at eval (./src/app/page.tsx:14:70)
    at (rsc)/./src/app/page.tsx (C:\GitHub\bnfc.cc\.next\server\app\page.js:234:1)
    at Function.__webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at async Promise.all (index 0)
digest: "235361954"
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at eval (./src/app/page.tsx:14:70)
    at (rsc)/./src/app/page.tsx (C:\GitHub\bnfc.cc\.next\server\app\page.js:234:1)
    at Function.__webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
digest: "4277508139"
TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at eval (webpack-internal:///(rsc)/./node_modules/swiper/swiper-react.mjs:132:93)
    at (rsc)/./node_modules/swiper/swiper-react.mjs (C:\GitHub\bnfc.cc\.next\server\vendor-chunks\swiper.js:70:1)
    at __webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/page.tsx:14:70)
    at (rsc)/./src/app/page.tsx (C:\GitHub\bnfc.cc\.next\server\app\page.js:234:1)
    at Function.__webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at async e9 (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:396554)
    at async tb (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400212)
    at async tS (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400773)
    at async tS (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400904)
    at async tR (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2130)
    at async C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2722 {
  digest: '4277508139'
}
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at eval (webpack-internal:///(rsc)/./node_modules/swiper/swiper-react.mjs:132:93)
    at (rsc)/./node_modules/swiper/swiper-react.mjs (C:\GitHub\bnfc.cc\.next\server\vendor-chunks\swiper.js:70:1)
    at __webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/page.tsx:14:70)
    at (rsc)/./src/app/page.tsx (C:\GitHub\bnfc.cc\.next\server\app\page.js:234:1)
    at Function.__webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at async e9 (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:396554)
    at async tb (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400212)
    at async tS (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400773)
    at async tS (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400904)
    at async tR (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2130)
    at async C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2722 {
  digest: '4277508139',
  page: '/'
}
 GET /_next/static/webpack/1e38f2a671d659d9.webpack.hot-update.json 404 in 719ms
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at eval (./src/app/page.tsx:14:70)
    at (rsc)/./src/app/page.tsx (C:\GitHub\bnfc.cc\.next\server\app\page.js:234:1)
    at Function.__webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at async Promise.all (index 0)
digest: "80749292"
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at eval (./src/app/page.tsx:14:70)
    at (rsc)/./src/app/page.tsx (C:\GitHub\bnfc.cc\.next\server\app\page.js:234:1)
    at Function.__webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at async Promise.all (index 0)
digest: "80749292"
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at eval (./src/app/page.tsx:14:70)
    at (rsc)/./src/app/page.tsx (C:\GitHub\bnfc.cc\.next\server\app\page.js:234:1)
    at Function.__webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
digest: "4277508139"
TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at eval (webpack-internal:///(rsc)/./node_modules/swiper/swiper-react.mjs:132:93)
    at (rsc)/./node_modules/swiper/swiper-react.mjs (C:\GitHub\bnfc.cc\.next\server\vendor-chunks\swiper.js:70:1)
    at __webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/page.tsx:14:70)
    at (rsc)/./src/app/page.tsx (C:\GitHub\bnfc.cc\.next\server\app\page.js:234:1)
    at Function.__webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at async e9 (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:396554)
    at async tb (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400212)
    at async tS (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400773)
    at async tS (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400904)
    at async tR (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2130)
    at async C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2722 {
  digest: '4277508139'
}
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at eval (webpack-internal:///(rsc)/./node_modules/swiper/swiper-react.mjs:132:93)
    at (rsc)/./node_modules/swiper/swiper-react.mjs (C:\GitHub\bnfc.cc\.next\server\vendor-chunks\swiper.js:70:1)
    at __webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/page.tsx:14:70)
    at (rsc)/./src/app/page.tsx (C:\GitHub\bnfc.cc\.next\server\app\page.js:234:1)
    at Function.__webpack_require__ (C:\GitHub\bnfc.cc\.next\server\webpack-runtime.js:33:42)
    at async e9 (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:396554)
    at async tb (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400212)
    at async tS (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400773)
    at async tS (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400904)
    at async tR (C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2130)
    at async C:\GitHub\bnfc.cc\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2722 {
  digest: '4277508139',
  page: '/'
}

### Expected Behavior

Slider shows

### Actual Behavior

Slider errors 

### Swiper version

11.1.4

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by ItsRemix** [comment]
You have in a reproduction site link a website with a bug

**Comment by mittalabhas1** [comment]
I am facing the same issue @nolimits4web 
> Clearly describe the issue including steps to reproduce when it is a bug.

The app doesn't load after following the instructions on the website 
<img width="978" alt="image" src="https://github.com/nolimits4web/swiper/assets/3685585/fda797de-8866-4517-804d-aa20d854d001">

> Make sure you fill in the earliest version that you know has the issue.

11.0.6

> Provide live link or JSFiddle/Codepen or website with isssue

https://codesandbox.io/p/devbox/nice-smoke-zs3cqt


Can you reopen this issue now?

**Comment by edicik** [comment]
> I am facing the same issue @nolimits4web
> 
> > Clearly describe the issue including steps to reproduce when it is a bug.
> 
> The app doesn't load after following the instructions on the website <img alt="image" width="978" src="https://private-user-images.githubusercontent.com/3685585/340137333-fda797de-8866-4517-804d-aa20d854d001.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NzQ4OTksIm5iZiI6MTcxODU3NDU5OSwicGF0aCI6Ii8zNjg1NTg1LzM0MDEzNzMzMy1mZGE3OTdkZS04ODY2LTQ1MTctODA0ZC1hYTIwZDg1NGQwMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTZUMjE0OTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzNjZmFlMTIyOGVjNDMxNTg4YzY3NzJiMmVlOWQ1YTRiNTBjM2NlZjU1NmRkZDk5NjY3OTJjMWVhZDg0Zjg4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SBO2FI41L4ua7h84ZInjc70fdMo-zCSGNec5Zwm8C_E">
> 
> > Make sure you fill in the earliest version that you know has the issue.
> 
> 11.0.6
> 
> > Provide live link or JSFiddle/Codepen or website with isssue
> 
> https://codesandbox.io/p/devbox/nice-smoke-zs3cqt
> 
> Can you reopen this issue now?

Add:
 - "use client"
 - import 'swiper/css'
 
 That will fix the issue
