### ISSUE TITLE
Error [RollupError]: Could not resolve "../shared/swiper-effect-utils.mjs" from "dist/modules/effect-cards.mjs"

### ISSUE THREAD

**Issue by benwallis** [nolimits4web/swiper#7791]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

n/a

### Bug description

Error when running using the custom build script and including "effect-cards".

Example build config:
```
import {
  parseSwiperBuildModulesEnv
} from './utils/helper.js';

const envBuildModules = parseSwiperBuildModulesEnv();

export const modules = envBuildModules || [
  'navigation',
  'effect-cards'
];

export default {
  modules,
};
```
After running `npm run build:prod` (using Node 20.10.0) I get the following error:

```
Error [RollupError]: Could not resolve "../shared/swiper-effect-utils.mjs" from "dist/modules/effect-cards.mjs"
    at error (file:///C:/www/swiper-git/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at ModuleLoader.handleInvalidResolvedId (file:///C:/www/swiper-git/node_modules/rollup/dist/es/shared/node-entry.js:17776:24)
    at file:///C:/www/swiper-git/node_modules/rollup/dist/es/shared/node-entry.js:17738:26 {
  code: 'UNRESOLVED_IMPORT',
  exporter: '../shared/swiper-effect-utils.mjs',
  id: 'C:\\www\\swiper-git\\dist\\modules\\effect-cards.mjs',
  watchFiles: [
    'C:\\www\\swiper-git\\dist\\swiper-bundle.mjs',
    'C:\\www\\swiper-git\\dist\\shared\\swiper-core.mjs',
    'C:\\www\\swiper-git\\dist\\modules\\navigation.mjs',
    'C:\\www\\swiper-git\\dist\\modules\\effect-cards.mjs',
    'C:\\www\\swiper-git\\dist\\shared\\utils.mjs'
  ]
}
```
Other effects such as fade build successfully.

### Expected Behavior

The build to be completed successfully.

### Actual Behavior

Build fails.

### Swiper version

11.1.14

### Platform/Target and Browser Versions

Windows 10 Firefox/Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by benwallis** [comment]
Same problem with 11.1.15.

I've found that it compiles if I only exclude cube, flip and creative.
If I exclude fade or coverflow then I get the rollup error above

This combination compiles:
```javascript
import {
  parseSwiperBuildModulesEnv
} from './utils/helper.js';

const envBuildModules = parseSwiperBuildModulesEnv();

export const modules = envBuildModules || [
  // 'virtual',
  //'keyboard',
  // 'mousewheel',
  'navigation',
  //'pagination',
  // 'scrollbar',
  // 'parallax',
  // 'zoom',
  // 'controller',
  'a11y',
  // 'history',
  // 'hash-navigation',
  //'autoplay',
  // 'thumbs',
  // 'free-mode',
  // 'grid',
  // 'manipulation',
  'effect-fade',
  //'effect-cube',
  //'effect-flip',
  'effect-coverflow',
  //'effect-creative',
  'effect-cards',
];

export default {
  modules,
};
```

**Comment by nolimits4web** [comment]
Check your logic or what your script does. The file "swiper-effect-utils.mjs" is not imported or references by any Swiper module/file
